### ISSUE TITLE
Front end tasks

### ISSUE THREAD

**Issue by tevissaur** [maxaeon/project-2#1]
- [x] Create wireframe
- [x] Research UX/UI of similar web apps
- [x] Build out base view
- [x] Build out nav bar
- [x] Build landing page
- [x] Build components

**Comment by maxaeon** [comment]
https://wireframe.cc/UuOc9H
![Screenshot (116)](https://user-images.githubusercontent.com/87254760/139540413-bbae6e25-eabd-4781-8865-b18db3705328.png)

**Comment by maxaeon** [comment]
![Screenshot (117)](https://user-images.githubusercontent.com/87254760/139540822-bd203443-3d02-4cf4-8e90-5f5b3ea791ed.png)
