### ISSUE TITLE
Hyperlink in Posts

### ISSUE THREAD

**Issue by X3N0TEK** [maxaeon/project-2#36]
Hyperlinks are italic and greyed out in Post. No functionality  present

**Comment by X3N0TEK** [comment]
this is also true within comments.

**Comment by maxaeon** [comment]
is that what's going on with the text "Length of the Grow Cycle
Optimal plotting patterns" on the landing page? because that text doesn't [successfully] link to anything from what i can tell

**Comment by maxaeon** [comment]
also, there's an issue with the "resources" link on heroku, on the top leftish-centerish of the page
